server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: users
          uri: lb://users
          predicates:
            - Path=/cine/api/v1/users/**
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/cine/api/v1/movie/**